#ifndef _CONCHITTA_CONSTANTS_MEGA_
#define _CONCHITTA_CONSTANTS_MEGA_

enum STATE
{
  START,
  GET_BOTTLES,
  GET_BOTTLES_STATE,
  GO_HOME,
  RELEASE_BOTTLES,
  AVOID_OBSTACLE,
  AVOID_OBSTACLE_HOME,
  STUCK_BOTTLE,
};

enum STATE_RPI
{
  RPI_GET_BOTTLES,
  RPI_GO_HOME,
  RPI_SHUTDOWN,
};

// #define SEND(x) Serial.println(x);
#define SEND(x) Bluetooth.send(x);

#define LED 13

#define MAX_SPEED 40
#define MAX_STEER 40
#define SLOW_SPEED 30
#define SLOW_STEER 30

#define MAX_BOTTLES 6
#define TIME_GOING_STRAIGHT 8000
#define TIME_TURNING_MAX 8000
#define TIME_TURNING_MIN 4000
#define RUNTIME 3000

#define TIME_END_GO_HOME 8 * 60000
#define TIME_END 10* 60000
#define TIME_TURNING_RELEASE_BOTTLES 1500

#define DYMX_ID_R 4
#define DYMX_ID_L 6
#define DYMX_ID_TRAP 1

// TODO: define IR
#define IR_FRONT A0
#define IR_TOP A1
// #define IR_CONTAINER 0

#define IR_FRONT_TH 280
#define IR_TOP_TH 280
#define IR_CONTAINER_TH 280

#define IR_OBST_FL A2
#define IR_OBST_FR A3
#define IR_OBST_SL A4
#define IR_OBST_SR A5

#define IR_OBST_FL_TH 0
#define IR_OBST_FR_TH 0
#define IR_OBST_SL_TH 0
#define IR_OBST_SR_TH 0

#define IR_OBST_SMOOTHING_RATIO 0.1
#define IR_OBST_LOWER_THRESHOLD 100

#define STUCK_BOTTLE_THRESHOLD 4000

#endif

