#ifndef _CONCHITTA_CONSTANTS_MEGA_
#define _CONCHITTA_CONSTANTS_MEGA_

enum STATE
{
  START,
  GET_BOTTLES,
  GET_BOTTLES_STATE,
  GO_HOME,
  RELEASE_BOTTLES,
  AVOID_OBSTACLE,
  AVOID_OBSTACLE_HOME,
  STUCK_BOTTLE,
};

enum STATE_RPI
{
  RPI_GET_BOTTLES,
  RPI_GO_HOME,
  RPI_SHUTDOWN,
};

// #define SEND(x) Serial.println(x);
#define SEND(x) Bluetooth.send(x);

#define LED 13

#define MAX_SPEED 50
#define MAX_STEER 50
#define SLOW_SPEED 35
#define SLOW_STEER 35

#define MAX_BOTTLES 11
#define TIME_GOING_STRAIGHT 8000
#define TIME_TURNING_MAX 2000
#define TIME_TURNING_MIN 500
#define RUNTIME 3000

#define TIME_END_GO_HOME 8 * 60000 //4000
#define TIME_END 10* 60000
#define TIME_TURNING_RELEASE_BOTTLES 1500

#define DYMX_ID_R 4
#define DYMX_ID_L 6
#define DYMX_ID_TRAP 1

// TODO: define IR
#define IR_FRONT A0
#define IR_TOP A1
// #define IR_CONTAINER 0

#define IR_FRONT_TH 215
#define IR_TOP_TH 240
#define BOTTLE_COUNT_MEDIAN_SIZE 7
#define BOTTLE_COUNT_DEAD_WINDOW 4000

#define BOTTLE_STUCK_MEDIAN_SIZE 7
#define LED_INTENSITY_MEDIAN_SIZE 9
#define HOME_INTENSITY_THRESHOLD 168
// #define IR_CONTAINER_TH 200

#define IR_OBST_SR A2
#define IR_OBST_FR A3
#define IR_OBST_FL A4
#define IR_OBST_SL A5

#define IR_OBST_FL_TH 0
#define IR_OBST_FR_TH 0
#define IR_OBST_SL_TH 0
#define IR_OBST_SR_TH 0

#define IR_OBST_SMOOTHING_RATIO 0.3
#define IR_OBST_LOWER_THRESHOLD 115
#define LINEARITY 0.3
#define LINEARITY_SPEED 0.2

#define BOTTLE_SMOOTHING_RATIO 0.2

#define STUCK_BOTTLE_THRESHOLD_TIME 6000
#define STUCK_BOTTLE_IN_THE_MIDDLE_IR_VALUE 223

#define BOTTLE_DETECTION_EXPIRATION_TIME 300
#define LED_DETECTION_EXPIRATION_TIME 200

#define LOW_SPEED_STEER_TURNING_THRESHOLD 10
#define SLOW_SPEED_BACK_WHEN_STUCK_IN_CORNER 10

#define TIME_GOING_STRAIGHT_GOING_HOME 4000
#define TIME_TURNING_MIN_GOING_HOME 2000
#define TIME_TURNING_MAX_GOING_HOME 5000

#endif

